apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-mysql
  labels:
    component: zabbix-cluster
    role: db
  namespace: devops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zabbix-cluster
        role: db
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: mysqlserver
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.io/mysql
        imagePullPolicy: Always
        args:
          - "--ignore-db-dir"
          - "lost+found"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "MYSQL_ROOT_PASSWORD"
          value: ""
        ports:
        - containerPort: 3300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: qcloudregistrykey
      volumes:
        - name: mysql-data
          hostPath:
            path: /tmp/mysqldata
