apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal: "21186"
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-p9oq3uc1
  labels:
    component: zabbix-server
    role: zabbix-server
  name: zabbix-server
  namespace: devops
spec:
  clusterIP: 172.21.255.11
  ports:
  - name: zabbix-server-port
    port: 10051
    protocol: TCP
    targetPort: 10051
  selector:
    component: zabbix-cluster
    role: zabbix-server
  sessionAffinity: None
  type: LoadBalancer
