apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: devops
  annotations:
    deployment.changecourse: RollingBack
  labels:
    component: zabbix-cluster
    role: zabbix-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zabbix-cluster
        role: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: ccr.ccs.tencentyun.com/zhulux_sre/zabbix-web:v0.1
        imagePullPolicy: Always
        name: zabbix-web
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_SERVER_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: 
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        - name: PHP_TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 80
          name: web-ui
          protocol: TCP
        - containerPort: 443
          name: web-ui-https
          protocol: TCP
      imagePullSecrets:
      - name: qcloudregistrykey
