apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.changecourse: RollingBack
  name: zabbix-agent
  labels:
    component: zabbix-cluster
    role: zabbix-agent
  namespace: devops
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: zabbix-cluster
        role: zabbix-agent
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: zabbix-agent
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: ccr.ccs.tencentyun.com/zhulux_sre/zabbix-agent:v0.2
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZBX_LISTENIP
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZBX_SERVER_HOST
          value: "zabbix-server"
        - name: ZBX_PASSIVE_ALLOW
          value: "false"
        - name: ZBX_STARTAGENTS
          value: "0"
        ports:
        - containerPort: 10050
          name: activer
          protocol: TCP
        volumeMounts:
        - name: hostname
          mountPath: /etc/hostname
        - name: rootfs
          mountPath: /rootfs
        - name: varrun
          mountPath: /var/run
        - name: disk1
          mountPath: /dev/vda
      imagePullSecrets:
      - name: qcloudregistrykey
      volumes:
      - name: hostname
        hostPath:
          path: /etc/hostname
      - name: rootfs
        hostPath:
          path: /
      - name: varrun
        hostPath:
          path: /var/run
      - name: disk1
        hostPath:
          path: /dev/vda
