apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal: "21186"
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-p9oq3uc1
  labels:
    component: zabbix-cluster
    role: zabbix-web
  name: zabbix-web
  namespace: devops
spec:
  clusterIP: 172.21.255.12
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    component: zabbix-cluster
    role: zabbix-web
  sessionAffinity: None
  type: LoadBalancer
